<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php

/*
dump(get_class($this));
dump($this->getData());
dump($this->getMethod());
dump($this->getMethod()->getData());
dump($this->getInfo());
dump($this->getInfo()->getData());
dump(get_class_methods(get_class($this)));
//dump(get_class_methods(get_class($this->getInfo())));
*/

?>

<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br/>

<?php if ($_info = $this->getInfo()): ?>

    <?php if ($_info->getMozgPspReference() == ''): ?>
        <?php echo Mage::helper('mozg_pagseguro')->__('Payment has not been processed yet.') ?> <br/>
    <?php else :?>

        <?php 

        //

        $order = $this->getMethod()->getInfoInstance()->getOrder();

        $realOrderId = $order->getRealOrderId();
        $incrementId = $order->getIncrementId();

        $storeId = $this->getMethod()->getInfoInstance()->getOrder()->getStoreId();

        //

        $pspReference = $this->htmlEscape($_info->getMozgPspReference());

        //

        if (Mage::app()->getStore()->isAdmin()){

        $url = Mage::helper('adminhtml')->getUrl('adminhtml/Pagseguro/consulta/', array('pspReference' => $pspReference) );
        $link = "javascript:openPopupsMozg('$url', 'WinXilinus', 'Link', 'PagSeguro', 'pagseguro');";

        echo Mage::helper('mozg_pagseguro')->__('PagSeguro PSP Reference: <a href="%s">%s</a>', $link, $pspReference) . ' <br/>';

        }

        //



        //

        ?>

    <?php endif;?>

    

    <?php if ($this->getInfo()->getMethod() == 'mozg_pagseguro_api_cc'): ?>
        <?php echo Mage::helper('mozg_pagseguro')->__('Name on the Card: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Credit Card Number: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Expiration Date: %s/%s', $this->htmlEscape($this->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?><br/>
        <?php if($this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments')) != "" && $this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments')) > 1): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Number of installments: %s', $this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments'))) ?><br/>
        <?php endif; ?>
        <?php if( isset($responseData) && ($_info->getMozgPspReference() != '') && empty($this->htmlEscape($this->getInfo()->getMozgAcquirerReference())) ): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Tid:: %s', $this->htmlEscape($responseData['Payment']['Tid'])) ?><br/>
        <?php endif; ?>
    <?php endif; ?>


    
    <?php if ($this->getInfo()->getMethod() == 'mozg_pagseguro_api_dc'): ?>
        <?php echo Mage::helper('mozg_pagseguro')->__('Name on the Card: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Credit Card Number: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Expiration Date: %s/%s', $this->htmlEscape($this->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?><br/>
        <?php if( ($_info->getMozgPspReference() != '') && empty($this->htmlEscape($this->getInfo()->getMozgAcquirerReference())) ): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Tid:: %s', $this->htmlEscape($responseData['Payment']['Tid'])) ?><br/>
        <?php endif; ?>
    <?php endif; ?>



    <?php if ($this->getInfo()->getMethod() == 'mozg_pagseguro_api_boleto'): ?>
        <?php $boleto = unserialize($this->getInfo()->getPoNumber())?>
        <?php echo Mage::helper('mozg_pagseguro')->__('Social Security Number: %s', $this->htmlEscape($boleto['social_security_number'])) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Firstname: %s', $this->htmlEscape($boleto['firstname'])) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Lastname: %s', $this->htmlEscape($boleto['lastname'])) ?><br/>

        <?php if($this->getInfo()->getOrder() != null): ?>
        <?php echo Mage::helper('mozg_pagseguro')->__('Boleto PDF: <a target="_blank" href="%s">Download</a>', $this->getInfo()->getOrder()->getMozgPaymentUrl()) ?><br/>
        <?php endif;?>

        <?php if( isset($responseData) ): ?>
        <?php echo Mage::helper('mozg_pagseguro')->__('Instructions: %s', $this->__($responseData['Payment']['Instructions'])) ?><br/>
        <?php endif;?>
    <?php endif; ?>



    <?php if ($this->getInfo()->getMethod() == 'mozg_pagseguro_api_eletronictransfer'): ?>
        <?php $boleto = unserialize($this->getInfo()->getPoNumber())?>
        <?php echo Mage::helper('mozg_pagseguro')->__('Social Security Number: %s', $this->htmlEscape($boleto['social_security_number'])) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Firstname: %s', $this->htmlEscape($boleto['firstname'])) ?><br/>
        <?php echo Mage::helper('mozg_pagseguro')->__('Lastname: %s', $this->htmlEscape($boleto['lastname'])) ?><br/>

        <?php if($this->getInfo()->getOrder() != null): ?>
        <?php echo Mage::helper('mozg_pagseguro')->__('EletronicTransfer PDF: <a target="_blank" href="%s">Download</a>', $this->getInfo()->getOrder()->getMozgPaymentUrl()) ?><br/>
        <?php endif;?>
    <?php endif; ?>



    <?php if ($this->getInfo()->getMethod() == 'mozg_pagseguro_api_padrao'): ?>
        <?php if($this->getInfo()->getOrder() != null): ?>
        <?php echo Mage::helper('mozg_pagseguro')->__('Payment URL: <a target="_blank" href="%s">Download</a>', $this->getInfo()->getOrder()->getMozgPaymentUrl()) ?><br/>
        <?php endif;?>
    <?php endif; ?>



    <?php if ($this->getInfo()->getMethod() == 'mozg_pagseguro_api_lightbox'): ?>
        <?php if($this->getInfo()->getOrder() != null): ?>

            <?php if (Mage::helper('mozg_pagseguro')->getConfigDataDemoMode($storeId) == 'Y') : ?>
                <!--Para integração em ambiente de testes no Sandbox use este link-->
                    <script
                        type="text/javascript"
                        src="https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js">
                    </script>
            <?php else : ?>
            <!--Para integração em ambiente de produção use este link-->
                    <script
                        type="text/javascript"
                        src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js">
                    </script>
            <?php endif; ?>

            <?php 

            $pspReference = $this->getInfo()->getOrder()->getPayment()->getMozgPspReference();

            $action = Mage::helper('mozg_pagseguro')->__("javascript:PagSeguroLightbox('%s');", $pspReference);

            echo Mage::helper('mozg_pagseguro')->__('Payment URL: <a href="#" onclick="%s">click here</a>', $action);

            ?><br/>
        <?php endif;?>
    <?php endif; ?>



    <?php if (Mage::app()->getStore()->isAdmin()): ?>
        <?php if($this->htmlEscape($this->getInfo()->getMozgAvsResult()) != ""): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Avs result: %s', $this->htmlEscape($this->getInfo()->getMozgAvsResult())) ?><br/>
        <?php endif; ?>
        <?php if($this->htmlEscape($this->getInfo()->getMozgCvcResult()) != ""): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Cvc result: %s', $this->htmlEscape($this->getInfo()->getMozgCvcResult())) ?><br/>
        <?php endif; ?>
        <?php if($this->htmlEscape($this->getInfo()->getMozgTotalFraudScore()) != ""): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Total fraud score: %s', $this->htmlEscape($this->getInfo()->getMozgTotalFraudScore())) ?><br/>
        <?php endif; ?>
        <?php if($this->htmlEscape($this->getInfo()->getMozgRefusalReasonRaw()) != ""): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Raw acquirer response: %s', $this->htmlEscape($this->getInfo()->getMozgRefusalReasonRaw())) ?><br/>
        <?php endif; ?>
        <?php if($this->htmlEscape($this->getInfo()->getMozgAuthCode()) != ""): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Authorisation code: %s', $this->htmlEscape($this->getInfo()->getMozgAuthCode())) ?><br/>
        <?php endif; ?>
        <?php if($this->htmlEscape($this->getInfo()->getMozgAcquirerReference()) != ""): ?>
            <?php echo Mage::helper('mozg_pagseguro')->__('Acquirer reference: %s', $this->htmlEscape($this->getInfo()->getMozgAcquirerReference())) ?><br/>
        <?php endif; ?>
    <?php endif; ?>

<?php endif;?>